name: whatsapp_clone
description: A new whatsapp clone for self learning.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  fl_country_code_picker: ^0.0.1
  flutter_test:
    sdk: flutter
  country_picker: ^2.0.16
  flutter_lints: ^2.0.0
  intl: ^0.17.0
  flutter_contacts:
  permission_handler: ^10.0.0
  contacts_service: ^0.6.3
  camera: ^0.9.4+19
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0


flutter:
  uses-material-design: true
  assets:
     - assets/whatsappicons.png
     - assets/metalogo.png
     - assets/arc.jpg
     - assets/welcomelogo.jpg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
